#pragma once

// Single-universe DMX512 output via UART1.
// Break is generated by inverting the UART TX line using the ESP-IDF driver.
// Timing: break ≥88µs, MAB ≥8µs, 250 kbaud 8N2.

#include "driver/uart.h"
#include "Arduino.h"

class DmxOutput {
public:
    bool begin(int pin) {
        Serial1.begin(250000, SERIAL_8N2, -1, pin);
        _ready = true;
        Serial.printf("DMX: TX on GPIO%d\n", pin);
        return true;
    }

    // Send start code 0x00 + up to 512 channel bytes.
    // Blocks ~104µs for break+MAB, then returns while UART sends async.
    void send(const uint8_t *data, int len = 512) {
        if (!_ready) return;
        if (len > 512) len = 512;

        Serial1.flush();  // wait for previous frame to finish

        // Break: invert TXD → pin goes LOW for ≥88µs
        uart_set_line_inverse(UART_NUM_1, UART_SIGNAL_TXD_INV);
        delayMicroseconds(92);

        // MAB: restore → pin goes HIGH for ≥8µs
        uart_set_line_inverse(UART_NUM_1, UART_SIGNAL_INV_DISABLE);
        delayMicroseconds(12);

        // Start code + channel data
        Serial1.write((uint8_t)0x00);
        Serial1.write(data, len);
    }

private:
    bool _ready = false;
};
